$(document).on 'turbolinks:load', ->
  $('.reply-expand').click (e) ->
    e.preventDefault()
    if e.data('expand') == false
      $('#replies').slideDown('fast')
      $('#reply-expand').data 'expand', true
      $('#reply-expand').html '<span class="fa fa-chevron-up"></span>'
    else
      $('#replies').slideUp('fast')
      $('#reply-expand').data 'expand', false
      $('#reply-expand').html '<span class="fa fa-chevron-down"></span>'
    return
  quantitiy = 0
  $('.quantity-right-plus').click (e) ->
    quantity = undefined
    e.preventDefault()
    quantity = parseInt($('#quantity-input').val())
    $('#quantity-input').val quantity + 1
    return
  $('.quantity-left-minus').click (e) ->
    quantity = undefined
    e.preventDefault()
    quantity = parseInt($('#quantity-input').val())
    if quantity > 1
      $('#quantity-input').val quantity - 1
    return
  $(window).on 'resize', ->
    if window.matchMedia('(max-width: 768px)').matches
      $('#product-form').addClass 'collapse'
    else
      $('#product-form').removeClass 'collapse'
    return
  $('.infinite-table').infinitePages
    loadingCallback: ->
      $('#state_window span').toggleClass 'fa fa-2x fa-refresh glyphicon-refresh-animate'
    errorCallback: ->
      $(this).button 'There was an error, please try again'
      $('#state_window span').toggleClass 'fa fa-2x fa-refresh glyphicon-refresh-animate'
    successCallback: ->
      $('#state_window span').toggleClass 'fa fa-2x fa-refresh glyphicon-refresh-animate'
    listSelector: '#product-list'
  $('.tag').on 'click', ->
    if 'false' == $(this).attr('data-checked')
      $(this).attr 'data-checked', 'true'
      $(this).addClass 'tag-checked'
    else
      $(this).attr 'data-checked', 'false'
      $(this).removeClass 'tag-checked'
    return
  $('#filter_btn').on 'click', ->
    array = undefined
    array = []
    $('a.tag', $('#sidebar-menu')).each ->
      if $(this).attr('data-checked') == 'true'
        array.push $(this).attr('data-tagid')
      return
    $.ajax
      url: '/products/filter.json'
      type: 'POST'
      data: 'tags': array
      success: (resp) ->
        $('#product-list').empty()
        if resp.length == 0
          $('#product-list').append '<h1> Empty </h1>'
        $.each resp, (index, value) ->
          $('#product-list').append '<div class="col-xs-12 col-sm-6 col-md-4">            <a href="' + resp[index].url + '"><img class="img-responsive" style="margin:auto;" src="' + resp[index].images + '"></a>            <div class="text-center">              <p>' + resp[index].name + '</p>              <strong style="color:#ed7999;">' + resp[index].price + '</strong>              <p></p>            </div>          </div>'
          return
        console.log resp
        return
    return
  return

# ---
# generated by js2coffee 2.2.0